name: Keep Streamlit App Alive

on:
  schedule:
    # Roda a cada 60 minutos
    - cron: '*/60 * * * *'
  workflow_dispatch: # Permite execução manual

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit App
        run: |
          curl -f https://locadoraiguacu.streamlit.app/ > /dev/null 2>&1 || echo "App pinged"
